autocraft:
  crafts:
    ten_craft:
      display-name: "&aTên hiển thị"
      glow: true
      materials:
        nguyen_lieu_1:
          material: MATERIAL_NAME
          amount: 8
      result:
        material: MATERIAL_NAME
        amount: 1
        display-name: "&e✨ Tên Sản Phẩm"
        lore:
          - "&7Mô tả"