name: Schoolminer
version: 1.0.0
main: com.schoolminer.Schoolminer
api-version: 1.21
author: school0107
description: Auto mine and auto kill plugin with autocraft
commands:
  automine:
    description: Tự động đào block
    usage: /automine
    permission: schoolminer.automine
  autokill:
    description: Tự động tấn công mob
    usage: /autokill
    permission: schoolminer.autokill
  autocraft:
    description: Tự động chế tạo
    usage: /autocraft <type> [off]
    permission: schoolminer.autocraft
  schoolminer:
    description: Quản lý plugin
    usage: /schoolminer reload
    permission: schoolminer.admin
permissions:
  schoolminer.automine:
    default: true
  schoolminer.autokill:
    default: true
  schoolminer.autocraft:
    default: op
  schoolminer.admin:
    default: op
  schoolminer.range.1:
    default: true
  schoolminer.range.2:
    default: op
  schoolminer.range.3:
    default: op
  schoolminer.range.4:
    default: op
  schoolminer.range.5:
    default: op
  # AutoCraft Permissions
  schoolminer.autocraft.go:
    default: op
  schoolminer.autocraft.da:
    default: op
  schoolminer.autocraft.kimcuong:
    default: op
  schoolminer.autocraft.sat:
    default: op
  schoolminer.autocraft.vang:
    default: op
